name: toolfinder_ai
description: A Flutter app for object detection using YOLOv8 ONNX model

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: ^0.10.0+1
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.3.2
  image: ^4.1.3
  onnxruntime: ^1.4.1
  path_provider: ^2.1.1
  glassmorphism: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true